name: 'Twilio Send SMS'
description: 'Send an SMS using Twilio'
inputs:
  from:
    description: 'This must be a Twilio phone number that you own, formatted with a "+" and country code.'
    required: true
  to:
    description: 'This must be a destination phone number formatted with a "+" and country code.'
    required: true
  body:
    description: 'Text message to send.'
    required: true
outputs:
  status:
    description: The status of the message.
  error:
    description: The error message.
runs:
  using: 'docker'
  image: 'Dockerfile'