on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Send an SMS using Twilio.
      id: sms
      uses: ankitjain28may/Twilio-Github-Action@master
      env:
        SID: ${{ secrets.SID }}
        AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
      with:
        from: ${{ secrets.FROM }}
        to: ${{ secrets.TO }}
        body: "Hello world"
    - name: Get the output status
      run: echo "The status of the message is ${{ steps.sms.outputs.status }}"
    - name: Get the error message
      run: echo "The status of the message is ${{ steps.sms.outputs.error }}"
